### ISSUE TITLE
Matchers ignore types of generic parameters

### ISSUE THREAD

**Issue by asomers** [kriomant/mockers#39]
Mockers allows mocking methods with generic parameters.  However, the matching logic ignores generic parameters' types.  This can result in the wrong expectation being matched, or in extreme cases a segfault.  Here's an example:
```rust
    fn generic_parameters(){
        #[mocked]
        pub trait A {
            fn foo<T>(&self, t:T) -> u32;
        }

        let scenario = Scenario::new();
        let mock = scenario.create_mock::<AMock>();
        scenario.expect(mock.foo_call(42u32).and_return(100u32));
        scenario.expect(mock.foo_call(42i16).and_return(1u32));
        assert_eq!(1u32, mock.foo(42i16));
        assert_eq!(100u32, mock.foo(42u32));
    }
```
This example fails with the error `panicked at 'A#0.foo was already called earlier`.   Here's another example
```rust
    fn generic_parameters(){
        const X: u32 = 5;
        #[mocked]
        pub trait A {
            fn foo<T>(&self, t:T) -> u32;
        }

        let scenario = Scenario::new();
        let mock = scenario.create_mock::<AMock>();
        scenario.expect(mock.foo_call(matchers::ANY).and_call(|p: &u32| *p));
        mock.foo(0u32);
    }
```
This example segfaults because the expectation is expecting a reference argument, but it gets an integer argument instead.

**Comment by kriomant** [comment]
Yes. you are right. I have to find a way to distinguish method instantiations at runtime.

**Comment by asomers** [comment]
For `'static` types, you can use `std::any::Any::type_id` and hash the type id's of the input and output types.  But unfortunately that doesn't work for non-`'static` types.

**Comment by kriomant** [comment]
I'll try to use `type_id`, if it wouldn't work, I have another idea using implementation specializations.

**Comment by kriomant** [comment]
`type_id` doesn't work, because it requires type parameter (not argument) to be `'static`, which is rarely the case. Additionally, it doesn't give type name for meaningful error messages.

In 0.13.1 I've implemented another approach with manual type registration. Read corresponding guide section. Errors are not great right now, especially: 1. type names are not part of method names right now - but they will; 2. when you forgot to register some type, it's not clear which type you should register. I'll try to improve these.

I've published this implementation early so that you can try and see whether this approach works at all. I close issue for now, but feel free to reopen it, if things are still unsafe or completely broken. Or create new issues for some minor complaints.
