### ISSUE TITLE
Getting error when using in sub modules

### ISSUE THREAD

**Issue by Biacode** [kriomant/mockers#8]
Hi,
The directory tree is:
project root
--context
----mod.rs
lib.rs
main.rs

The provided example are works well in case when it's placed in to lib.rs in the root directory.
But when I place it in to sub modules for example mod.rs in context module Ive getting error:
https://gist.github.com/Biacode/99b3b36758702cc16a3dda42d574e09a
Any ideas?
Thanks

**Comment by kriomant** [comment]
Can you please provide complete example crate causing error? I'm not really sure what exactly should be moved to submodule: struct definition, function, tests or all of them.

**Comment by Biacode** [comment]
I think the best way to show this scenario is real code.
I attached it below
[error_scenario.tar.gz](https://github.com/kriomant/mockers/files/546021/error_scenario.tar.gz)

**Comment by kriomant** [comment]
If you try to compile provided code, you'll notice compiler warnings:

```
warning: unused attribute, #[warn(unused_attributes)] on by default
 --> src/context/context.rs:1:1
  |
1 | #![plugin(mockers_macros)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: crate-level attribute should be in the root module, #[warn(unused_attributes)] on by default
 --> src/context/context.rs:1:1
  |
1 | #![plugin(mockers_macros)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

What is says is that this attribute has no effect because it must be located in root module, not in submodule. This is Rust requirement and it is not specific to `mockers` library. So in fact you have not imported macro from `mockers` library.

Move declaration to root module. You can find fixed crate [here](https://www.dropbox.com/s/iwrzv026ra2rdjh/error_scenario.tgz?dl=0).

**Comment by Biacode** [comment]
@kriomant Thank you!
Sorry for that, I just started using rust...
Please close this issue.
